# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
snd-soc-axg-card-objs := axg-card.o
snd-soc-axg-memif-objs := axg-memif.o
snd-soc-axg-tdm-objs := axg-tdm.o
snd-soc-axg-tdmif-objs := axg-tdmif.o

obj-$(CONFIG_SND_MESON_AXG_CARD) += snd-soc-axg-card.o
obj-$(CONFIG_SND_MESON_AXG_MEMIF) += snd-soc-axg-memif.o
obj-$(CONFIG_SND_MESON_AXG_TDM) += snd-soc-axg-tdm.o
obj-$(CONFIG_SND_MESON_AXG_TDM) += snd-soc-axg-tdmif.o
